### ISSUE TITLE
Clicking Run simulation multiple times causes download csv to append

### ISSUE THREAD

**Issue by seanfreiburg** [boknows/cFIREsim-open#12] opened 2015-02-11 18:08 UTC
Problem: Clicking Run simulation multiple times causes "download csv" to append to the last "download csv" which looks like this "download CSVdownload CSVdownload CSVdownload CSVdownload CSV"
http://i.imgur.com/tw7nvgV.png

Expected behavior: The "download csv" to be replaced by the newest, or to append on with a new line.

**Comment by boknows** [comment] 2015-02-11 18:43
This was fixed in a recent commit.  Please refresh the page a couple of times and try again.  I could not reproduce this anymore.

**Closed by boknows** 2015-02-11 18:43 UTC

**Comment by seanfreiburg** [comment] 2015-02-11 19:35
Yep, it's fixed.
